eureka.instance.preferIpAddress=true
#eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

spring.redis.host=redis-16554.crce263.ap-south-1-1.ec2.cloud.redislabs.com
spring.redis.port=16554
spring.redis.password=W7RHKKEHYM1azYcKw3uiUMux1p5PMorZ


greeting.msg=Goog AfterNoon
