eureka.instance.preferIpAddress=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

spring.redis.host=redis-15832.c305.ap-south-1-1.ec2.redns.redis-cloud.com
spring.redis.port=15832
spring.redis.password=FtZEASIkYLOQqCy24e0IMUvnaDQBwbD0


greeting.msg=Goog AfterNoon
