spring.application.name=user-policy-service
server.port=8081

eureka.instance.preferIpAddress=true
#eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka

# Enabling H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/crmdb
spring.h2.console.settings.web-allow-others=true
spring.datasource.url=jdbc:h2:mem:user-policy-db
spring.data.jpa.repositories.bootstrap-mode=default
spring.datasource.username=db
spring.datasource.password=db

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.redis.host=redis-15832.c305.ap-south-1-1.ec2.redns.redis-cloud.com
spring.redis.port=15832
spring.redis.password=FtZEASIkYLOQqCy24e0IMUvnaDQBwbD0

spring.main.allow-bean-definition-overriding=true
